"""Shared Matrix relation and replay-suppression helpers.

Both CoPaw Matrix channel implementations are deployed in AgentTeams.  Keep
the wire-level relation parsing and generation here so replies behave the same
regardless of which channel registry loads the implementation.
"""
from __future__ import annotations

from collections import deque
import json
import os
from pathlib import Path
from typing import Any, Mapping, MutableMapping


GENERATED_EVENT_KEY = "io.agentteams.generated"
THREAD_ROOT_META_KEY = "thread_root_event_id"
MATRIX_THREAD_ROOT_META_KEY = "matrix_thread_root_event_id"
MATRIX_TRIGGER_EVENT_META_KEY = "matrix_trigger_event_id"
TRIGGERING_EVENT_META_KEY = "triggering_event_id"


def event_content(event: Any) -> dict[str, Any]:
    """Return an event's Matrix content dictionary, tolerating test doubles."""
    source = getattr(event, "source", {}) or {}
    if not isinstance(source, Mapping):
        return {}
    content = source.get("content", {}) or {}
    return dict(content) if isinstance(content, Mapping) else {}


def is_generated_event(event: Any) -> bool:
    """Return whether *event* was generated by an AgentTeams channel helper."""
    marker = event_content(event).get(GENERATED_EVENT_KEY)
    return isinstance(marker, Mapping)


def generated_marker(kind: str) -> dict[str, Any]:
    """Build the namespaced marker attached to internal Matrix messages."""
    return {GENERATED_EVENT_KEY: {"kind": kind, "version": 1}}


def inbound_relation_meta(event: Any) -> dict[str, str]:
    """Preserve the original thread root and the event being answered.

    A reply to an existing thread must keep the thread's original root while
    ``m.in_reply_to`` identifies the triggering event.  For a new top-level
    message, the triggering event becomes the root of the response thread.
    """
    triggering_event = str(getattr(event, "event_id", "") or "")
    root_event = triggering_event
    relates_to = event_content(event).get("m.relates_to", {}) or {}
    if isinstance(relates_to, Mapping) and relates_to.get("rel_type") == "m.thread":
        related_root = relates_to.get("event_id")
        if isinstance(related_root, str) and related_root:
            root_event = related_root

    meta: dict[str, str] = {}
    if root_event:
        meta[THREAD_ROOT_META_KEY] = root_event
        meta[MATRIX_THREAD_ROOT_META_KEY] = root_event
    if triggering_event:
        meta[MATRIX_TRIGGER_EVENT_META_KEY] = triggering_event
        meta[TRIGGERING_EVENT_META_KEY] = triggering_event
    return meta


def apply_thread_relation(
    content: MutableMapping[str, Any],
    meta: Mapping[str, Any] | None,
) -> None:
    """Attach an MSC3440 thread relation, including the triggering reply."""
    if not isinstance(meta, Mapping):
        return
    root = (
        meta.get(MATRIX_THREAD_ROOT_META_KEY)
        or meta.get(THREAD_ROOT_META_KEY)
        or meta.get("matrix_own_thread_root_event_id")
    )
    if not isinstance(root, str) or not root:
        return

    relation: dict[str, Any] = {
        "rel_type": "m.thread",
        "event_id": root,
        "is_falling_back": False,
    }
    triggering = (
        meta.get(MATRIX_TRIGGER_EVENT_META_KEY)
        or meta.get(TRIGGERING_EVENT_META_KEY)
        or meta.get("event_id")
    )
    if isinstance(triggering, str) and triggering:
        relation["m.in_reply_to"] = {"event_id": triggering}
    content["m.relates_to"] = relation


def atomic_write_text(path: Path, value: str) -> None:
    """Atomically replace a small runtime-state file and fsync its contents."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        with temporary.open("w", encoding="utf-8", newline="") as handle:
            handle.write(value)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        try:
            temporary.unlink(missing_ok=True)
        except OSError:
            pass


class RecentEventLedger:
    """Bounded, persisted ledger of successfully handled Matrix event IDs."""

    def __init__(self, path: Path | None, capacity: int = 2048) -> None:
        self.path = path
        self.capacity = max(1, capacity)
        loaded: list[str] = []
        if path and path.exists():
            try:
                value = json.loads(path.read_text(encoding="utf-8"))
                if isinstance(value, list):
                    loaded = [item for item in value if isinstance(item, str) and item]
            except (OSError, ValueError, TypeError):
                loaded = []
        self._events: deque[str] = deque(loaded[-self.capacity :])
        self._event_set = set(self._events)

    def contains(self, event_id: str | None) -> bool:
        return bool(event_id) and event_id in self._event_set

    def remember(self, event_id: str | None) -> None:
        if not event_id or event_id in self._event_set:
            return
        while len(self._events) >= self.capacity:
            self._event_set.discard(self._events.popleft())
        self._events.append(event_id)
        self._event_set.add(event_id)
        if self.path:
            atomic_write_text(
                self.path,
                json.dumps(list(self._events), ensure_ascii=False, separators=(",", ":")),
            )
